import { IMAGE_MOCK } from './IMAGE_MOCK';

export const POSTS = [
  {
    postId: 'dfnkasklfn',
    isCat: true,
    postHeading: 'THIS IS A',
    postDescription: 'POST',
    image: IMAGE_MOCK,
    totalLikes: 1021011,
    userLike: true,
    postedBy: 'IsraCum',
  },
  {
    postId: 'dfnkasklfn',
    isCat: true,
    postHeading: 'THIS IS A',
    postDescription: 'POST',
    image: IMAGE_MOCK,
    totalLikes: 1021011,
    userLike: false,
    postedBy: 'IsraCum',
  },
  {
    postId: 'dfnkasklfn',
    isCat: true,
    postHeading: 'THIS IS A',
    postDescription: 'POST',
    image: IMAGE_MOCK,
    totalLikes: 1021011,
    userLike: false,
    postedBy: 'IsraCum',
  },
  {
    postId: 'dfnkasklfn',
    isCat: true,
    postHeading: 'THIS IS A',
    postDescription: 'POST',
    image: IMAGE_MOCK,
    totalLikes: 1021011,
    userLike: true,
    postedBy: 'IsraCum',
  },
  {
    postId: 'dfnkasklfn',
    isCat: true,
    postHeading: 'THIS IS A',
    postDescription: 'POST',
    image: IMAGE_MOCK,
    totalLikes: 1021011,
    userLike: true,
    postedBy: 'IsraCum',
  },
  {
    postId: 'dfnkasklfn',
    isCat: true,
    postHeading: 'THIS IS A',
    postDescription: 'POST',
    image: IMAGE_MOCK,
    totalLikes: 1021011,
    userLike: true,
    postedBy: 'IsraCum',
  },
  {
    postId: 'dfnkasklfn',
    isCat: true,
    postHeading: 'THIS IS A',
    postDescription: 'POST',
    image: IMAGE_MOCK,
    totalLikes: 1021011,
    userLike: true,
    postedBy: 'IsraCum',
  },
];
